spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 50MB
  thymeleaf:
    cache: false
  # 数据库相关设置
  datasource:
    # 数据源如果不设置，使用默认的Tomcat数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost/user?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      username: root
      password: cjp123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 初始化大小，最小，最大
      initial-size: 8
      min-idle: 8
      max-active: 500
      # 配置获取连接等待超时的时间(毫秒)
      max-wait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 6000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat, wall, log4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
  redis:
    host: 192.168.5.194
    port: 6379
    timeout: 60000
#    cluster:
#      #     集群信息
#      nodes: 192.18.5.194:6380,192.168.5.194:6381,192.168.5.194:6382,192.168.5.194:6383,192.168.5.194:6384,192.168.5.194:6385
#      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#      maxRedirects: 3
#      timeout: 60000
    password: cjp123456
# mybatis相关配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: user
#spring.datasource.url=jdbc:mysql://localhost/user?serverTimezone=UTC&useSSl=false
#spring.datasource.username=root
#spring.datasource.password=cjp123456
#
## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=192.168.5.194
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=cjp123456
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.jedis.pool.max-active=20
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.jedis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.jedis.pool.max-idle=10
## 连接池中的最小空闲连接
#spring.redis.jedis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=1000
#
#
#mybatis.configuration.map-underscore-to-camel-case=true